#
# 
#
name: Update Maven Repo

on:
  push:
    branches: [ test-push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: megamek
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      working-directory: megamek
      run: chmod +x gradlew
    - name: Publish Maven Repo with Gradle
      working-directory: megamek
      run: ./gradlew publishPublishMMLibraryPublicationToMavenRepository
    - name: Checkout Maven Repo
      uses: actions/checkout@v2
      with:
        repository: sixlettervariables/mavenrepo
        path: mavenrepo
    - name: Copy Maven Outputs to Repo
      run: |
        cp -r megamek/megamek/build/mavenrepo/ mavenrepo/
    - name: Inspect git status output
      working-directory: mavenrepo
      run: |
        git status
    - name: Commit changes to the Maven Repo
      working-directory: mavenrepo
      run: |
        git add .
        git config user.email ${{ github.event.pusher.email }}
        git config user.name ${{ github.event.pusher.name }}
        git commit -m "MegaMek ${{ github.event.after }}"
    - name: Push changes to the Maven Repo
      env:
        GIT_PAT: ${{ secrets.GH_PAT_FOR_MM }}
      working-directory: mavenrepo
      run: |
        git push "https://sixlettervariables:${GIT_PAT}@github.com/sixlettervariables/mavenrepo.git" HEAD:master
